filename_to_ev = {
    #jwst nircam blaze
    'jwst_nircam_speceff':'crnircamblaze',
    #jwst nircam detector
    'jwst_nircam_h2rg_ipckernel':'crnircamdet',
    #jwst nircam dispersion
    'jwst_nircam_disp':'crnircamdisp',
    #jwst nircam filter
    'jwst_nircam_f070w_trans':'crnircamfilt',
    'jwst_nircam_f090w_trans':'crnircamfilt',
    'jwst_nircam_f115w_trans':'crnircamfilt',
    'jwst_nircam_f140m_trans':'crnircamfilt',
    'jwst_nircam_f150w2_trans':'crnircamfilt',
    'jwst_nircam_f150w_trans':'crnircamfilt',
    'jwst_nircam_f162m_trans':'crnircamfilt',
    'jwst_nircam_f164n_trans':'crnircamfilt',
    'jwst_nircam_f182m_trans':'crnircamfilt',
    'jwst_nircam_f187n_trans':'crnircamfilt',
    'jwst_nircam_f200w_trans':'crnircamfilt',
    'jwst_nircam_f210m_trans':'crnircamfilt',
    'jwst_nircam_f212n_trans':'crnircamfilt',
    'jwst_nircam_f250m_trans':'crnircamfilt',
    'jwst_nircam_f277w_trans':'crnircamfilt',
    'jwst_nircam_f300m_trans':'crnircamfilt',
    'jwst_nircam_f322w2_trans':'crnircamfilt',
    'jwst_nircam_f323n_trans':'crnircamfilt',
    'jwst_nircam_f335m_trans':'crnircamfilt',
    'jwst_nircam_f356w_trans':'crnircamfilt',
    'jwst_nircam_f360m_trans':'crnircamfilt',
    'jwst_nircam_f405n_trans':'crnircamfilt',
    'jwst_nircam_f410m_trans':'crnircamfilt',
    'jwst_nircam_f430m_trans':'crnircamfilt',
    'jwst_nircam_f444w_trans':'crnircamfilt',
    'jwst_nircam_f460m_trans':'crnircamfilt',
    'jwst_nircam_f466n_trans':'crnircamfilt',
    'jwst_nircam_f470n_trans':'crnircamfilt',
    'jwst_nircam_f480m_trans ':'crnircamfilt',
    'jwst_nircam_lw-lyot_trans_modmean':'crnircamfilt',
    'jwst_nircam_moda_com_substrate_trans':'crnircamfilt',
    'jwst_nircam_sw-lyot_trans_modmean':'crnircamfilt',
    #'jwst_nircam_optical'
    'jwst_nircam_internaloptics_throughput':'crnircamopt',
    'jwst_nircam_lw-lyot_trans_modmean':'crnircamopt',
    'jwst_nircam_lw_dbs':'crnircamopt',
    'jwst_nircam_moda_com_substrate_trans':'crnircamopt',
    'jwst_nircam_sw-lyot_trans_modmean':'crnircamopt',
    'jwst_nircam_sw_dbs':'crnircamopt',
    'jwst_nircam_wlp4':'crnircamopt',
    'jwst_nircam_wlp8':'crnircamopt',
    #'jwst_nircam_psfs' #none
    #'jwst_nircam_qe' #too many
    #jwst_niriss_blaze
    'jwst_niriss_gr150c-ordm1_speceff': 'crnirissblaze',
    'jwst_niriss_gr150c-ordp2_speceff': 'crnirissblaze',
    'jwst_niriss_gr150c-ordp3_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordm1_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordp1_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordp2_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordp3_speceff': 'crnirissblaze',
    'jwst_niriss_gr700xd-ord1_speceff': 'crnirissblaze',
    'jwst_niriss_gr700xd-ord2_speceff': 'crnirissblaze',
    'jwst_niriss_gr700xd-ord3_speceff': 'crnirissblaze',
    #jwst niriss dispersion
    'jwst_niriss_gr150c-ordm1_disp':'crnirissdisp',
    'jwst_niriss_gr150c-ordp1_disp':'crnirissdisp',
    'jwst_niriss_gr150c-ordp2_disp':'crnirissdisp',
    'jwst_niriss_gr150c-ordp3_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordm1_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordp1_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordp2_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordp3_disp':'crnirissdisp',
    'jwst_niriss_gr700xd-ord1_disp':'crnirissdisp',
    'jwst_niriss_gr700xd-ord2_disp':'crnirissdisp',
    'jwst_niriss_gr700xd-ord3_disp':'crnirissdisp',
    #jwst niriss filters
    'jwst_niriss_f090w_trans':'crnirissfilt',
    'jwst_niriss_f115w_trans':'crnirissfilt',
    'jwst_niriss_f140m_trans':'crnirissfilt',
    'jwst_niriss_f150w_trans':'crnirissfilt',
    'jwst_niriss_f158m_trans':'crnirissfilt',
    'jwst_niriss_f200w_trans':'crnirissfilt',
    'jwst_niriss_f277w_trans':'crnirissfilt',
    'jwst_niriss_f356w_trans':'crnirissfilt',
    'jwst_niriss_f380m_trans':'crnirissfilt',
    'jwst_niriss_f430m_trans':'crnirissfilt',
    'jwst_niriss_f444w_trans':'crnirissfilt',
    'jwst_niriss_f480m_trans':'crnirissfilt',
    'jwst_niriss_nrm_trans':'crnirissfilt',
    #jwst niriss masks
    'jwst_niriss_soss-256-ord1_mask':'crnirissmask',
    'jwst_niriss_soss-256-ord2_mask':'crnirissmask',
    'jwst_niriss_soss-256-ord3_mask':'crnirissmask',
    'jwst_niriss_soss-96-ord1_mask':'crnirissmask',
    #jwsy niriss optical
    'jwst_niriss_internaloptics-clear_throughput':'crnirissopt',
    'jwst_niriss_internaloptics-clearp_throughput':'crnirissopt',
    'jwst_niriss_internaloptics_throughput':'crnirissopt',
    #'jwst_niriss_psfs' #None
    #jwst niriss qe
    'jwst_niriss_h2rg_qe':'crnirissqe',
    #jwst niriss wavepix
    'jwst_niriss_soss-256-ord1_trace':'crnirisswave',
    'jwst_niriss_soss-256-ord2_trace':'crnirisswave',
    'jwst_niriss_soss-256-ord3_trace':'crnirisswave',
    'jwst_niriss_soss-96-ord1_trace':'crnirisswave',
    'jwst_niriss_soss-96-ord2_trace':'crnirisswave',
    'jwst_niriss_soss-96-ord3_trace':'crnirisswave',
    #jwst niriss xtras #None
    #jwst telescope
    'jwst_telescope':'cttelescope'
}

file_to_pandeia = {
    #jwst nircam blaze
    'jwst_nircam_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/blaze/',
    #jwst nircam detector
    'jwst_nircam_h2rg_ipckernel':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/detector/',
    #jwst nircam dispersion
    'jwst_nircam_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/dispersion/',
    #jwst nircam filter
    'jwst_nircam_f070w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f090w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f115w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f140m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f150w2_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f150w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f162m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f164n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f182m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f187n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f200w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f210m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f212n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f250m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f277w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f300m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f322w2_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f323n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f335m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f356w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f360m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f405n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f410m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f430m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f444w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f460m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f466n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f470n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_f480m_trans ':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_lw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_moda_com_substrate_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    'jwst_nircam_sw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filter/',
    #'jwst_nircam_optical'
    'jwst_nircam_internaloptics_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_lw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_lw_dbs':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_moda_com_substrate_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_sw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_sw_dbs':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_wlp4':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_wlp8':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    #'jwst_nircam_psfs' #none
    #'jwst_nircam_qe' #too many
    #jwst_niriss_blaze
    'jwst_niriss_gr150c-ordm1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150c-ordp2_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150c-ordp3_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordm1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordp1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordp2_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordp3_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr700xd-ord1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr700xd-ord2_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr700xd-ord3_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    #jwst niriss dispersion
    'jwst_niriss_gr150c-ordm1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150c-ordp1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150c-ordp2_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150c-ordp3_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordm1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordp1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordp2_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordp3_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr700xd-ord1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr700xd-ord2_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr700xd-ord3_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    #jwst niriss filters
    'jwst_niriss_f090w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f115w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f140m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f150w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f158m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f200w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f277w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f356w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f380m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f430m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f444w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f480m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_nrm_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    #jwst niriss masks
    'jwst_niriss_soss-256-ord1_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    'jwst_niriss_soss-256-ord2_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    'jwst_niriss_soss-256-ord3_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    'jwst_niriss_soss-96-ord1_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    #jwsy niriss optical
    'jwst_niriss_internaloptics-clear_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/optical/',
    'jwst_niriss_internaloptics-clearp_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/optical/',
    'jwst_niriss_internaloptics_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/optical/',
    #'jwst_niriss_psfs' #None
    #jwst niriss qe
    'jwst_niriss_h2rg_qe':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/qe/',
    #jwst niriss wavepix
    'jwst_niriss_soss-256-ord1_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-256-ord2_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-256-ord3_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-96-ord1_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-96-ord2_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-96-ord3_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    #jwst niriss xtras #None
    #jwst telescope
    'jwst_telescope':'/grp/hst/cdbs/work/jwst/delivery/pandeia/telescope/'
}
