filename_to_ev = {
    #jwst nircam blaze
    'jwst_nircam_speceff':'crnircamblaze',
    #jwst nircam detector
    'jwst_nircam_h2rg_ipckernel':'crnircamdet',
    #jwst nircam dispersion
    'jwst_nircam_disp':'crnircamdisp',
    #jwst nircam filter
    'jwst_nircam_f070w_trans':'crnircamfilt',
    'jwst_nircam_f090w_trans':'crnircamfilt',
    'jwst_nircam_f115w_trans':'crnircamfilt',
    'jwst_nircam_f140m_trans':'crnircamfilt',
    'jwst_nircam_f150w2_trans':'crnircamfilt',
    'jwst_nircam_f150w_trans':'crnircamfilt',
    'jwst_nircam_f162m_trans':'crnircamfilt',
    'jwst_nircam_f164n_trans':'crnircamfilt',
    'jwst_nircam_f182m_trans':'crnircamfilt',
    'jwst_nircam_f187n_trans':'crnircamfilt',
    'jwst_nircam_f200w_trans':'crnircamfilt',
    'jwst_nircam_f210m_trans':'crnircamfilt',
    'jwst_nircam_f212n_trans':'crnircamfilt',
    'jwst_nircam_f250m_trans':'crnircamfilt',
    'jwst_nircam_f277w_trans':'crnircamfilt',
    'jwst_nircam_f300m_trans':'crnircamfilt',
    'jwst_nircam_f322w2_trans':'crnircamfilt',
    'jwst_nircam_f323n_trans':'crnircamfilt',
    'jwst_nircam_f335m_trans':'crnircamfilt',
    'jwst_nircam_f356w_trans':'crnircamfilt',
    'jwst_nircam_f360m_trans':'crnircamfilt',
    'jwst_nircam_f405n_trans':'crnircamfilt',
    'jwst_nircam_f410m_trans':'crnircamfilt',
    'jwst_nircam_f430m_trans':'crnircamfilt',
    'jwst_nircam_f444w_trans':'crnircamfilt',
    'jwst_nircam_f460m_trans':'crnircamfilt',
    'jwst_nircam_f466n_trans':'crnircamfilt',
    'jwst_nircam_f470n_trans':'crnircamfilt',
    'jwst_nircam_f480m_trans ':'crnircamfilt',
    'jwst_nircam_lw-lyot_trans_modmean':'crnircamfilt',
    'jwst_nircam_moda_com_substrate_trans':'crnircamfilt',
    'jwst_nircam_sw-lyot_trans_modmean':'crnircamfilt',
    #'jwst_nircam_optical'
    'jwst_nircam_internaloptics_throughput':'crnircamopt',
    'jwst_nircam_lw-lyot_trans_modmean':'crnircamopt',
    'jwst_nircam_lw_dbs':'crnircamopt',
    'jwst_nircam_moda_com_substrate_trans':'crnircamopt',
    'jwst_nircam_sw-lyot_trans_modmean':'crnircamopt',
    'jwst_nircam_sw_dbs':'crnircamopt',
    'jwst_nircam_wlp4':'crnircamopt',
    'jwst_nircam_wlp8':'crnircamopt',
    #'jwst_nircam_psfs' #none
    #'jwst_nircam_qe'
    'jwst_nircam_lw_qe':'crnircamqe',
    'jwst_nircam_qe':'crnircamqe',
    'jwst_nircam_sw_qe':'crnircamqe',
    #jwst_niriss_blaze
    'jwst_niriss_gr150c-ordm1_speceff': 'crnirissblaze',
    'jwst_niriss_gr150c-ordp2_speceff': 'crnirissblaze',
    'jwst_niriss_gr150c-ordp3_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordm1_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordp1_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordp2_speceff': 'crnirissblaze',
    'jwst_niriss_gr150r-ordp3_speceff': 'crnirissblaze',
    'jwst_niriss_gr700xd-ord1_speceff': 'crnirissblaze',
    'jwst_niriss_gr700xd-ord2_speceff': 'crnirissblaze',
    'jwst_niriss_gr700xd-ord3_speceff': 'crnirissblaze',
    #jwst niriss dispersion
    'jwst_niriss_gr150c-ordm1_disp':'crnirissdisp',
    'jwst_niriss_gr150c-ordp1_disp':'crnirissdisp',
    'jwst_niriss_gr150c-ordp2_disp':'crnirissdisp',
    'jwst_niriss_gr150c-ordp3_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordm1_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordp1_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordp2_disp':'crnirissdisp',
    'jwst_niriss_gr150r-ordp3_disp':'crnirissdisp',
    'jwst_niriss_gr700xd-ord1_disp':'crnirissdisp',
    'jwst_niriss_gr700xd-ord2_disp':'crnirissdisp',
    'jwst_niriss_gr700xd-ord3_disp':'crnirissdisp',
    #jwst niriss filters
    'jwst_niriss_f090w_trans':'crnirissfilt',
    'jwst_niriss_f115w_trans':'crnirissfilt',
    'jwst_niriss_f140m_trans':'crnirissfilt',
    'jwst_niriss_f150w_trans':'crnirissfilt',
    'jwst_niriss_f158m_trans':'crnirissfilt',
    'jwst_niriss_f200w_trans':'crnirissfilt',
    'jwst_niriss_f277w_trans':'crnirissfilt',
    'jwst_niriss_f356w_trans':'crnirissfilt',
    'jwst_niriss_f380m_trans':'crnirissfilt',
    'jwst_niriss_f430m_trans':'crnirissfilt',
    'jwst_niriss_f444w_trans':'crnirissfilt',
    'jwst_niriss_f480m_trans':'crnirissfilt',
    'jwst_niriss_nrm_trans':'crnirissfilt',
    #jwst niriss masks
    'jwst_niriss_soss-256-ord1_mask':'crnirissmask',
    'jwst_niriss_soss-256-ord2_mask':'crnirissmask',
    'jwst_niriss_soss-256-ord3_mask':'crnirissmask',
    'jwst_niriss_soss-96-ord1_mask':'crnirissmask',
    #jwsy niriss optical
    'jwst_niriss_internaloptics-clear_throughput':'crnirissopt',
    'jwst_niriss_internaloptics-clearp_throughput':'crnirissopt',
    'jwst_niriss_internaloptics_throughput':'crnirissopt',
    #'jwst_niriss_psfs' #None
    #jwst niriss qe
    'jwst_niriss_h2rg_qe':'crnirissqe',
    #jwst niriss wavepix
    'jwst_niriss_soss-256-ord1_trace':'crnirisswave',
    'jwst_niriss_soss-256-ord2_trace':'crnirisswave',
    'jwst_niriss_soss-256-ord3_trace':'crnirisswave',
    'jwst_niriss_soss-96-ord1_trace':'crnirisswave',
    'jwst_niriss_soss-96-ord2_trace':'crnirisswave',
    'jwst_niriss_soss-96-ord3_trace':'crnirisswave',
    #jwst niriss xtras #None
    #jwst nirspec blaze
    'jwst_nirspec_g140h_speceff':'crnirspecbl',
    'jwst_nirspec_g235m_speceff':'crnirspecbl',
    'jwst_nirspec_mirror_speceff':'crnirspecbl',
    'jwst_nirspec_g140m_speceff':'crnirspecbl',
    'jwst_nirspec_g395h_speceff':'crnirspecbl',
    'jwst_nirspec_prism_speceff':'crnirspecbl',
    'jwst_nirspec_g235h_speceff':'crnirspecbl',
    'jwst_nirspec_g395m_speceff':'crnirspecbl',
    #jwst nirspec detector
    'jwst_nirspec_ipckernel':'crnirspecdet',
    #jwst nirspec dispersion
    'jwst_nirspec_g140h_disp':'crnirspecdisp',
    'jwst_nirspec_g235m_disp':'crnirspecdisp',
    'jwst_nirspec_prism_disp':'crnirspecdisp',
    'jwst_nirspec_g140m_disp':'crnirspecdisp',
    'jwst_nirspec_g395h_disp':'crnirspecdisp',
    'jwst_nirspec_g235h_disp':'crnirspecdisp',
    'jwst_nirspec_g395m_disp':'crnirspecdisp',
    #jwst nirspec filters
    'jwst_nirspec_clear_trans':'crnirspecfilt',
    'jwst_nirspec_f110w_trans':'crnirspecfilt',
    'jwst_nirspec_f290lp_trans':'crnirspecfilt',
    'jwst_nirspec_f070lp_trans':'crnirspecfilt',
    'jwst_nirspec_f140x_trans':'crnirspecfilt',
    'jwst_nirspec_f100lp_trans':'crnirspecfilt',
    'jwst_nirspec_f170lp_trans':'crnirspecfilt',
    #jwst nirspec optical
    'jwst_nirspec_ifu_internaloptics_throughput':'crnirspecopt',
    'jwst_nirspec_mos_internaloptics_throughput':'crnirspecopt',
    #jwst nirspec psfs: NONE
    #jwst nirspec qe
    'jwst_nirspec_qe':'crnirspecqe',
    #jwst miri blaze
    'jwst_miri_ch1_speceff':'crmiriblaze',
    'jwst_miri_ch2b_speceff':'crmiriblaze',
    'jwst_miri_ch4_speceff':'crmiriblaze',
    'jwst_miri_ch1a_speceff':'crmiriblaze',
    'jwst_miri_ch2c_speceff':'crmiriblaze',
    'jwst_miri_ch4a_speceff':'crmiriblaze',
    'jwst_miri_ch1b_speceff':'crmiriblaze',
    'jwst_miri_ch3_speceff':'crmiriblaze',
    'jwst_miri_ch4b_speceff':'crmiriblaze',
    'jwst_miri_ch1c_speceff':'crmiriblaze',
    'jwst_miri_ch3a_speceff':'crmiriblaze',
    'jwst_miri_ch4c_speceff':'crmiriblaze',
    'jwst_miri_ch2_speceff':'crmiriblaze',
    'jwst_miri_ch3b_speceff':'crmiriblaze',
    'jwst_miri_p750l_speceff':'crmiriblaze',
    'jwst_miri_ch2a_speceff':'crmiriblaze',
    'jwst_miri_ch3c_speceff':'crmiriblaze',
    #jwst miri detector: NONE
    #jwst miri dispersion
    'jwst_miri_ch1-long_disp':'crmiridisp',
    'jwst_miri_ch2-short_disp':'crmiridisp',
    'jwst_miri_ch4-medium_disp':'crmiridisp',
    'jwst_miri_ch1-medium_disp':'crmiridisp',
    'jwst_miri_ch3-long_disp':'crmiridisp',
    'jwst_miri_ch4-short_disp':'crmiridisp',
    'jwst_miri_ch1-short_disp':'crmiridisp',
    'jwst_miri_ch3-medium_disp':'crmiridisp',
    'jwst_miri_p750l_disp':'crmiridisp',
    'jwst_miri_ch2-long_disp':'crmiridisp',
    'jwst_miri_ch3-short_disp':'crmiridisp',
    'jwst_miri_ch2-medium_disp':'crmiridisp',
    'jwst_miri_ch4-long_disp':'crmiridisp',
    #jwst miri filters
    'jwst_miri_coro_f1065c_trans':'crmirifilt',
    'jwst_miri_f1280w_trans':'crmirifilt',
    'jwst_miri_imager_f1280w_trans':'crmirifilt',
    'jwst_miri_coro_f1140c_trans':'crmirifilt',
    'jwst_miri_f1500w_trans':'crmirifilt',
    'jwst_miri_imager_f1500w_trans':'crmirifilt',
    'jwst_miri_coro_f1550c_trans':'crmirifilt',
    'jwst_miri_f1550c_trans':'crmirifilt',
    'jwst_miri_imager_f1800w_trans':'crmirifilt',
    'jwst_miri_coro_f2300c_trans':'crmirifilt',
    'jwst_miri_f1800w_trans':'crmirifilt',
    'jwst_miri_imager_f2100w_trans':'crmirifilt',
    'jwst_miri_f0560w_trans':'crmirifilt',
    'jwst_miri_f2100w_trans':'crmirifilt',
    'jwst_miri_imager_f2550w_trans':'crmirifilt',
    'jwst_miri_f0770w_trans':'crmirifilt',
    'jwst_miri_f2300c_trans':'crmirifilt',
    'jwst_miri_imager_f2550wr_trans':'crmirifilt',
    'jwst_miri_f1000w_trans':'crmirifilt',
    'jwst_miri_f2550w_trans':'crmirifilt',
    'jwst_miri_imager_f560w_trans':'crmirifilt',
    'jwst_miri_f1065c_trans':'crmirifilt',
    'jwst_miri_f2550wr_trans':'crmirifilt',
    'jwst_miri_imager_f770w_trans':'crmirifilt',
    'jwst_miri_f1130w_trans':'crmirifilt',
    'jwst_miri_imager_f1000w_trans':'crmirifilt',
    'jwst_miri_f1140c_trans':'crmirifilt',
    'jwst_miri_imager_f1130w_trans':'crmirifilt',
    #jwst miri optical
    'jwst_miri_dich1-l_refl':'crmiriopt',
    'jwst_miri_dich2-l_refl':'crmiriopt',
    'jwst_miri_dich3-l_refl':'crmiriopt',
    'jwst_miri_dich1-l_trans':'crmiriopt',
    'jwst_miri_dich2-l_trans':'crmiriopt',
    'jwst_miri_dich3-l_trans':'crmiriopt',
    'jwst_miri_dich1-m_refl':'crmiriopt',
    'jwst_miri_dich2-m_refl':'crmiriopt',
    'jwst_miri_dich3-m_refl':'crmiriopt',
    'jwst_miri_dich1-m_trans':'crmiriopt',
    'jwst_miri_dich2-m_trans':'crmiriopt',
    'jwst_miri_dich3-m_trans':'crmiriopt',
    'jwst_miri_dich1-s_refl':'crmiriopt',
    'jwst_miri_dich2-s_refl':'crmiriopt',
    'jwst_miri_dich3-s_refl':'crmiriopt',
    'jwst_miri_dich1-s_trans':'crmiriopt',
    'jwst_miri_dich2-s_trans':'crmiriopt',
    'jwst_miri_dich3-s_trans':'crmiriopt',
    #jwst miri psfs: NONE
    #jwst miri qe
    'jwst_miri_imager_qe':'crmiriqe',
    'jwst_miri_mrs-lw_qe':'crmiriqe',
    'jwst_miri_imaging_qe':'crmiriqe',
    'jwst_miri_mrs-sw_qe':'crmiriqe',
    #jwst telescope
    'jwst_telescope':'cttelescope'
}

file_to_pandeia = {
    #jwst nircam blaze
    'jwst_nircam_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/blaze/',
    #jwst nircam detector
    'jwst_nircam_h2rg_ipckernel':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/detector/',
    #jwst nircam dispersion
    'jwst_nircam_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/dispersion/',
    #jwst nircam filter
    'jwst_nircam_f070w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f090w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f115w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f140m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f150w2_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f150w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f162m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f164n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f182m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f187n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f200w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f210m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f212n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f250m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f277w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f300m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f322w2_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f323n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f335m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f356w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f360m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f405n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f410m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f430m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f444w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f460m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f466n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f470n_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_f480m_trans ':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_lw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_moda_com_substrate_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    'jwst_nircam_sw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/filters/',
    #'jwst_nircam_optical'
    'jwst_nircam_internaloptics_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_lw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_lw_dbs':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_moda_com_substrate_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_sw-lyot_trans_modmean':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_sw_dbs':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_wlp4':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    'jwst_nircam_wlp8':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nircam/optical/',
    #'jwst_nircam_psfs' #none
    #'jwst_nircam_qe' #too many
    #jwst_niriss_blaze
    'jwst_niriss_gr150c-ordm1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150c-ordp2_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150c-ordp3_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordm1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordp1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordp2_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr150r-ordp3_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr700xd-ord1_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr700xd-ord2_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    'jwst_niriss_gr700xd-ord3_speceff': '/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/blaze/',
    #jwst niriss dispersion
    'jwst_niriss_gr150c-ordm1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150c-ordp1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150c-ordp2_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150c-ordp3_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordm1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordp1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordp2_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr150r-ordp3_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr700xd-ord1_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr700xd-ord2_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    'jwst_niriss_gr700xd-ord3_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/dispersion/',
    #jwst niriss filters
    'jwst_niriss_f090w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f115w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f140m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f150w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f158m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f200w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f277w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f356w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f380m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f430m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f444w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_f480m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    'jwst_niriss_nrm_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/filters/',
    #jwst niriss masks
    'jwst_niriss_soss-256-ord1_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    'jwst_niriss_soss-256-ord2_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    'jwst_niriss_soss-256-ord3_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    'jwst_niriss_soss-96-ord1_mask':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/masks/',
    #jwsy niriss optical
    'jwst_niriss_internaloptics-clear_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/optical/',
    'jwst_niriss_internaloptics-clearp_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/optical/',
    'jwst_niriss_internaloptics_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/optical/',
    #'jwst_niriss_psfs' #None
    #jwst niriss qe
    'jwst_niriss_h2rg_qe':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/qe/',
    #jwst niriss wavepix
    'jwst_niriss_soss-256-ord1_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-256-ord2_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-256-ord3_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-96-ord1_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-96-ord2_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    'jwst_niriss_soss-96-ord3_trace':'/grp/hst/cdbs/work/jwst/delivery/pandeia/niriss/wavepix/',
    #jwst niriss xtras #None
    #jwst nirspec blaze
    'jwst_nirspec_g140h_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    'jwst_nirspec_g235m_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    'jwst_nirspec_mirror_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    'jwst_nirspec_g140m_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    'jwst_nirspec_g395h_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    'jwst_nirspec_prism_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    'jwst_nirspec_g235h_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    'jwst_nirspec_g395m_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/blaze/',
    #jwst nirspec detector
    'jwst_nirspec_ipckernel':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/detector/',
    #jwst nirspec dispersion
    'jwst_nirspec_g140h_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/dispersion/',
    'jwst_nirspec_g235m_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/dispersion/',
    'jwst_nirspec_prism_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/dispersion/',
    'jwst_nirspec_g140m_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/dispersion/',
    'jwst_nirspec_g395h_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/dispersion/',
    'jwst_nirspec_g235h_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/dispersion/',
    'jwst_nirspec_g395m_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/dispersion/',
    #jwst nirspec filters
    'jwst_nirspec_clear_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/filters/',
    'jwst_nirspec_f110w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/filters/',
    'jwst_nirspec_f290lp_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/filters/',
    'jwst_nirspec_f070lp_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/filters/',
    'jwst_nirspec_f140x_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/filters/',
    'jwst_nirspec_f100lp_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/filters/',
    'jwst_nirspec_f170lp_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/filters/',
    #jwst nirspec optical
    'jwst_nirspec_ifu_internaloptics_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/optical/',
    'jwst_nirspec_mos_internaloptics_throughput':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/optical/',
    #jwst nirspec psfs: NONE
    #jwst nirspec qe
    'jwst_nirspec_qe':'/grp/hst/cdbs/work/jwst/delivery/pandeia/nirspec/qe/',
    #jwst miri blaze
    'jwst_miri_ch1_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch2b_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch4_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch1a_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch2c_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch4a_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch1b_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch3_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch4b_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch1c_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch3a_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch4c_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch2_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch3b_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_p750l_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch2a_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    'jwst_miri_ch3c_speceff':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/blaze/',
    #jwst miri detector: NONE
    #jwst miri dispersion
    'jwst_miri_ch1-long_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch2-short_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch4-medium_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch1-medium_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch3-long_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch4-short_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch1-short_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch3-medium_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_p750l_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch2-long_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch3-short_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch2-medium_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    'jwst_miri_ch4-long_disp':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/dispersion/',
    #jwst miri filters
    'jwst_miri_coro_f1065c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1280w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f1280w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_coro_f1140c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1500w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f1500w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_coro_f1550c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1550c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f1800w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_coro_f2300c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1800w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f2100w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f0560w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f2100w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f2550w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f0770w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f2300c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f2550wr_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1000w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f2550w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f560w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1065c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f2550wr_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f770w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1130w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f1000w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_f1140c_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    'jwst_miri_imager_f1130w_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/filters/',
    #jwst miri optical
    'jwst_miri_dich1-l_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich2-l_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich3-l_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich1-l_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich2-l_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich3-l_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich1-m_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich2-m_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich3-m_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich1-m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich2-m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich3-m_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich1-s_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich2-s_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich3-s_refl':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich1-s_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich2-s_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    'jwst_miri_dich3-s_trans':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/optical/',
    #jwst miri psfs: NONE
    #jwst miri qe
    'jwst_miri_imager_qe':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/qe/',
    'jwst_miri_mrs-lw_qe':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/qe/',
    'jwst_miri_imaging_qe':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/qe/',
    'jwst_miri_mrs-sw_qe':'/grp/hst/cdbs/work/jwst/delivery/pandeia/miri/qe/',
    #jwst telescope
    'jwst_telescope':'/grp/hst/cdbs/work/jwst/delivery/pandeia/telescope/'
}
